//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference1
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/WcfService2")]
    public partial class CompositeType : object
    {
        
        private bool BoolValueField;
        
        private string StringValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue
        {
            get
            {
                return this.BoolValueField;
            }
            set
            {
                this.BoolValueField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue
        {
            get
            {
                return this.StringValueField;
            }
            set
            {
                this.StringValueField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CargaCatalogoLavanderia", ReplyAction="http://tempuri.org/IService1/CargaCatalogoLavanderiaResponse")]
        string CargaCatalogoLavanderia();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CargaCatalogoLavanderia", ReplyAction="http://tempuri.org/IService1/CargaCatalogoLavanderiaResponse")]
        System.Threading.Tasks.Task<string> CargaCatalogoLavanderiaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CargatuluServicios", ReplyAction="http://tempuri.org/IService1/CargatuluServiciosResponse")]
        string CargatuluServicios();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CargatuluServicios", ReplyAction="http://tempuri.org/IService1/CargatuluServiciosResponse")]
        System.Threading.Tasks.Task<string> CargatuluServiciosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CargaEMPLEADOS", ReplyAction="http://tempuri.org/IService1/CargaEMPLEADOSResponse")]
        string CargaEMPLEADOS();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CargaEMPLEADOS", ReplyAction="http://tempuri.org/IService1/CargaEMPLEADOSResponse")]
        System.Threading.Tasks.Task<string> CargaEMPLEADOSAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CargaORDENES", ReplyAction="http://tempuri.org/IService1/CargaORDENESResponse")]
        string CargaORDENES();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CargaORDENES", ReplyAction="http://tempuri.org/IService1/CargaORDENESResponse")]
        System.Threading.Tasks.Task<string> CargaORDENESAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CargatuluVentas", ReplyAction="http://tempuri.org/IService1/CargatuluVentasResponse")]
        string CargatuluVentas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CargatuluVentas", ReplyAction="http://tempuri.org/IService1/CargatuluVentasResponse")]
        System.Threading.Tasks.Task<string> CargatuluVentasAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CargaORDEN_DETALLE", ReplyAction="http://tempuri.org/IService1/CargaORDEN_DETALLEResponse")]
        string CargaORDEN_DETALLE();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CargaORDEN_DETALLE", ReplyAction="http://tempuri.org/IService1/CargaORDEN_DETALLEResponse")]
        System.Threading.Tasks.Task<string> CargaORDEN_DETALLEAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Carga_Dato_Extra", ReplyAction="http://tempuri.org/IService1/Carga_Dato_ExtraResponse")]
        string Carga_Dato_Extra(int IdCatalogo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Carga_Dato_Extra", ReplyAction="http://tempuri.org/IService1/Carga_Dato_ExtraResponse")]
        System.Threading.Tasks.Task<string> Carga_Dato_ExtraAsync(int IdCatalogo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CargaClientes", ReplyAction="http://tempuri.org/IService1/CargaClientesResponse")]
        string CargaClientes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CargaClientes", ReplyAction="http://tempuri.org/IService1/CargaClientesResponse")]
        System.Threading.Tasks.Task<string> CargaClientesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CargaVentasMensuales", ReplyAction="http://tempuri.org/IService1/CargaVentasMensualesResponse")]
        string CargaVentasMensuales();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CargaVentasMensuales", ReplyAction="http://tempuri.org/IService1/CargaVentasMensualesResponse")]
        System.Threading.Tasks.Task<string> CargaVentasMensualesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CargaTopServicios", ReplyAction="http://tempuri.org/IService1/CargaTopServiciosResponse")]
        string CargaTopServicios();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CargaTopServicios", ReplyAction="http://tempuri.org/IService1/CargaTopServiciosResponse")]
        System.Threading.Tasks.Task<string> CargaTopServiciosAsync();

        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RegistrarOperacion", ReplyAction="http://tempuri.org/IService1/RegistrarOperacionResponse")]
        string RegistrarOperacion(int id_cliente, int id_trabajo, int id_empleado, decimal total, string estado_pago, string metodo_pago);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RegistrarOperacion", ReplyAction="http://tempuri.org/IService1/RegistrarOperacionResponse")]
        System.Threading.Tasks.Task<string> RegistrarOperacionAsync(int id_cliente, int id_trabajo, int id_empleado, decimal total, string estado_pago, string metodo_pago);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        ServiceReference1.CompositeType GetDataUsingDataContract(ServiceReference1.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<ServiceReference1.CompositeType> GetDataUsingDataContractAsync(ServiceReference1.CompositeType composite);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface IService1Channel : ServiceReference1.IService1, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<ServiceReference1.IService1>, ServiceReference1.IService1
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public Service1Client() : 
                base(Service1Client.GetDefaultBinding(), Service1Client.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IService1.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(EndpointConfiguration endpointConfiguration) : 
                base(Service1Client.GetBindingForEndpoint(endpointConfiguration), Service1Client.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(Service1Client.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(Service1Client.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public string GetData(int value)
        {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value)
        {
            return base.Channel.GetDataAsync(value);
        }
        
        public string CargaCatalogoLavanderia()
        {
            return base.Channel.CargaCatalogoLavanderia();
        }
        
        public System.Threading.Tasks.Task<string> CargaCatalogoLavanderiaAsync()
        {
            return base.Channel.CargaCatalogoLavanderiaAsync();
        }
        
        public string CargatuluServicios()
        {
            return base.Channel.CargatuluServicios();
        }
        
        public System.Threading.Tasks.Task<string> CargatuluServiciosAsync()
        {
            return base.Channel.CargatuluServiciosAsync();
        }
        
        public string CargaEMPLEADOS()
        {
            return base.Channel.CargaEMPLEADOS();
        }
        
        public System.Threading.Tasks.Task<string> CargaEMPLEADOSAsync()
        {
            return base.Channel.CargaEMPLEADOSAsync();
        }
        
        public string CargaORDENES()
        {
            return base.Channel.CargaORDENES();
        }
        
        public System.Threading.Tasks.Task<string> CargaORDENESAsync()
        {
            return base.Channel.CargaORDENESAsync();
        }
        
        public string CargatuluVentas()
        {
            return base.Channel.CargatuluVentas();
        }
        
        public System.Threading.Tasks.Task<string> CargatuluVentasAsync()
        {
            return base.Channel.CargatuluVentasAsync();
        }
        
        public string CargaORDEN_DETALLE()
        {
            return base.Channel.CargaORDEN_DETALLE();
        }
        
        public System.Threading.Tasks.Task<string> CargaORDEN_DETALLEAsync()
        {
            return base.Channel.CargaORDEN_DETALLEAsync();
        }
        
        public string Carga_Dato_Extra(int IdCatalogo)
        {
            return base.Channel.Carga_Dato_Extra(IdCatalogo);
        }
        
        public System.Threading.Tasks.Task<string> Carga_Dato_ExtraAsync(int IdCatalogo)
        {
            return base.Channel.Carga_Dato_ExtraAsync(IdCatalogo);
        }
        
        public string CargaClientes()
        {
            return base.Channel.CargaClientes();
        }
        
        public System.Threading.Tasks.Task<string> CargaClientesAsync()
        {
            return base.Channel.CargaClientesAsync();
        }
        
        public string CargaVentasMensuales()
        {
            return base.Channel.CargaVentasMensuales();
        }
        
        public System.Threading.Tasks.Task<string> CargaVentasMensualesAsync()
        {
            return base.Channel.CargaVentasMensualesAsync();
        }
        
        public string CargaTopServicios()
        {
            return base.Channel.CargaTopServicios();
        }
        
        public System.Threading.Tasks.Task<string> CargaTopServiciosAsync()
        {
            return base.Channel.CargaTopServiciosAsync();
        }

        public string RegistrarOperacion(int id_cliente, int id_trabajo, int id_empleado, decimal total, string estado_pago, string metodo_pago)
        {
            return base.Channel.RegistrarOperacion(id_cliente, id_trabajo, id_empleado, total, estado_pago, metodo_pago);
        }
        
        public System.Threading.Tasks.Task<string> RegistrarOperacionAsync(int id_cliente, int id_trabajo, int id_empleado, decimal total, string estado_pago, string metodo_pago)
        {
            return base.Channel.RegistrarOperacionAsync(id_cliente, id_trabajo, id_empleado, total, estado_pago, metodo_pago);
        }
        
        public ServiceReference1.CompositeType GetDataUsingDataContract(ServiceReference1.CompositeType composite)
        {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.CompositeType> GetDataUsingDataContractAsync(ServiceReference1.CompositeType composite)
        {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IService1))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IService1))
            {
                return new System.ServiceModel.EndpointAddress("http://proyecto8voalphonse.somee.com/Service1.svc");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return Service1Client.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IService1);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return Service1Client.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IService1);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IService1,
        }
    }
}
